image:
  pullPolicy: IfNotPresent
  registry:
    url: pierrearmand/video-api-service
  tag: master

labels:
  environment: development
  framework: node
  repo: video-api-service
  task: service
  instance: default

resources:
  limits:
    memory: 105Mi
  requests:
    cpu: 30m

strategy:
  maxUnavailable: 0
  maxSurge: 1

environment: development
config_file: development.ini

min_replicas: 2
max_replicas: 10
